create table "files" ("id" integer generated by default as identity, "time_mills" bigint not null, "author" varchar(255), "file_download_uri" varchar(255), "file_name" varchar(255), "size" integer, primary key ("id"));
    create table "person" ("id" integer generated by default as identity, "email" varchar(255), "password" varchar(255), "username" varchar(255), primary key ("id"));
    create table "person_roles" ("person_id" integer not null, "roles_id" integer not null, primary key ("person_id", "roles_id"));
    create table "roles" ("id" integer generated by default as identity, "name" varchar(20), primary key ("id"));
    alter table "person_roles" add constraint "FK841xtf8abvv9nbpegukyjl62h" foreign key ("roles_id") references "roles";
    alter table "person_roles" add constraint "FKmalkosy2x87xodt2rlr9q7lly" foreign key ("person_id") references "person";